---
title: "Cleaning up data"
author: "Tori Burt"
date: "2023-05-04"
output: html_document
verison: "4.2.2"
---

```{r loading packages}

library(tidyverse)
library(data.table)
library(cimir)
library(anytime)

```

```{r cleaning up data}

#load data
data <- read.csv("data/Fishplant_2022_May_4_2023_SG.csv", na.strings = c("", "NA"))

#change column names
names(data)[names(data) == "Wind_speed.km.hr."] <- "WindSpeed"
names(data)[names(data) == "Number.of.Boxes"] <- "Box"
names(data)[names(data) == "Plant_Lights_on.off"] <- "Lights"
names(data)[names(data) == "Weather..Fog..Cloud..Rain.Clear."] <- "Weather"

#filter for fishplant workers only
data <- filter(data, Observer %like% "Sherry Green" | Observer == "Cheryl")

#make sure data is categorized correctly
data$Date <- anytime(data$Date)

#make columns that just contain year, month, and day of year
data$Date <- as.POSIXlt(data$Date, format = "%m/%d/%Y")

data$Year <- data$Date$year
data$Month <- data$Date$mon + 1
data$Date <- as.POSIXct(data$Date)
data$yDate <- yday(data$Date)
data$Total_LESP <- as.numeric(data$Total_LESP)

#classify variables 
data$Lunar <- gsub("moon does not pass meridian on this day", 100, data$Lunar)
data$Lunar <- as.numeric(data$Lunar)

data$WindSpeed <- as.numeric(data$WindSpeed)

data$yDate <- as.numeric(data$yDate)

data$Box <- as.factor(data$Box)

data$Year <- as.factor(data$Year)

data$Lights <- factor(data$Lights, levels = c("on","off"))

#save the data file
save(data, file = "Data.Rda")

```
