---
title: "Plotting_BdV_Map_TVB"
author: "Tori Burt"
date: "2023-05-08"
output: html_document
---

```{r loading packages}

library(tidyverse)
library(sf)
library(ggpubr)
library(legendMap)

```

```{r preparing data for plotting}

#import shape file
nl.map <- st_read(file.path("gpr_000b11a_e/gpr_000b11a_e.shp")) 

#shape file for the 2011 Census by Geo Statistics Canada, available at: https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-2011-eng.cfm

#setting map boundaries
xmin <- -53 #zoomed in
xmax <- -52.6
ymin <- 48
ymax <- 48.25

```

```{r mapping data}

#creating plot of canada
map1 <- ggplot() +
  theme_bw() + #aesthetic parameters
  coord_sf() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(colour = 'black'),
        axis.text.y = element_text(colour = 'black')) +
  scale_x_continuous(labels = function(x) paste0(x, '\u00B0', "W")) +
  scale_y_continuous(labels = function(x) paste0(x, '\u00B0', "N")) +
  geom_sf(data = nl.map, #inserting the shape file
          colour = 'black',
          fill = 'grey') +
  labs(x = 'Longitude', #naming labels
       y = 'Latitude') +
  annotate("text", x = -140, y= 82, label= "A", size = 7) +
  geom_point(aes(x = -52.89831, y = 48.09780), colour="red", size = 2) 

map2 <- ggplot() +
  theme_bw() + #aesthetic parameters
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(colour = 'black'),
        axis.text.y = element_text(colour = 'black')) +
  geom_sf(data = nl.map, #inserting the shape file
          colour = 'black',
          fill = 'grey') +
  scale_x_continuous(labels = function(x) paste0(x, '\u00B0', "W")) +
  scale_y_continuous(labels = function(x) paste0(x, '\u00B0', "N")) +
  coord_sf(xlim = c(xmin, xmax), #setting map boundaries
           ylim = c(ymin, ymax)) +
  labs(x = 'Longitude', #naming labels
       y = 'Latitude') +
  geom_point(aes(x = -52.89831, y = 48.09780), colour="red", size = 2) +
  geom_point(aes(x = -52.802, y = 48.135), colour="red", size = 2) +
  annotate("text", x= -53, y= 48.25, label= "B", size = 7) +
  annotate("text", x= -52.93, y= 48.11, label= "Bay de Verde", size = 3.5) +
  annotate("text", x= -52.8, y= 48.17, label= "Baccalieu Island", size = 3.5) +
  scale_bar(lon = -52.75, lat = 48, distance_lon = 5, distance_lat = 2, distance_legend = 3, dist_unit = "km", orientation = F)

jpeg(filename = "figures/Map_Canada_BdV.jpeg", width = 20, height = 10, units = "cm", res = 2000)
ggarrange(map1, map2)
dev.off()
```
